"""
CV strip (control) — generated by /sim-experiment on 2026-06-25
Goal: Conduction velocity in a healthy ventricular strip (control)
Manifest: ./MANIFEST.md   (the confirmed parameters — the accountability record)
Run:  conda run -n heart-conduction python run.py
"""

import cardiac_core as cc

# ============================================================
# PARAMETERS  — edit these
# ============================================================
LENGTH_CM      = 2.0       # tissue length (cm)
WIDTH_CM       = 0.5       # tissue width (cm)
DX             = 0.01      # grid spacing (cm); smaller = finer + slower
SIGMA_I        = 1.74      # intracellular conductivity (mS/cm)
SIGMA_E        = 6.25      # extracellular conductivity (mS/cm); lower = weaker coupling (fibrosis-like)
IONIC          = "ttp06"   # cell model: "ttp06" or "ord"
STIM_WIDTH_CM  = 0.05      # stimulate the left edge up to this x (cm)
STIM_START_MS  = 1.0
STIM_AMP       = -80.0     # µA/µF (negative = depolarizing)
T_END_MS       = 40.0
SAVE_EVERY_MS  = 0.5
SLUG           = "cv-strip-control"
MAKE_MEDIA     = True      # render standardized propagation video + APD figure
# ============================================================

Nx, Ny = round(LENGTH_CM / DX), round(WIDTH_CM / DX)

grid = cc.Grid(Nx, Ny, DX)
cond = cc.ConductivityConfig.bidomain(SIGMA_I, SIGMA_E, chi=1400.0)
stim = {"region": lambda x, y: x < STIM_WIDTH_CM, "start_time": STIM_START_MS,
        "duration": 2.0, "amplitude": STIM_AMP}

sim = cc.monodomain(grid, IONIC, cond, stim)
result = sim.run(t_end=T_END_MS, save_every=SAVE_EVERY_MS)

# --- measurement ---
cv = result.cv(x1=round(0.2 / DX), x2=round(1.0 / DX), y=Ny // 2)
print(f"conduction velocity = {cv:.1f} cm/s")

# --- standardized media (regenerable → gitignored media/lab/_sim_outputs/; set MAKE_MEDIA=False to skip) ---
if MAKE_MEDIA:
    from cardiac_core import propagation_video, apd_map_figure
    print("video:", propagation_video(result, SLUG, bulk=True))
    print("apd:  ", apd_map_figure(result, SLUG, bulk=True))
