# -*- coding: utf-8 -*-
"""StorageTanks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X48Z8hPbodYucLOVkGqPLJ5Ewc1oue3
"""

import numpy as np
import time
import cv2

class StorageTank:
    def __init__(self, id, max_volume,threshold=45.0,maxpump=10.0):
        self.id = id
        self.max_volume = max_volume
        self.current_volume = 0
        self.virtual_volume = 0
        self.connections = list()
        self.threshold = threshold
        self.max_pump = maxpump
        self.pumpfactor = np.sqrt((self.max_volume-self.threshold))
        self.isInlet = False
        self.isOutlet = False

    def checkpump(self, tank):
      if (self.current_volume>self.threshold):
          if (self.current_volume > tank.current_volume):
            pump_amount = StorageTank.GetPumpAmount(self.current_volume,self.threshold,self.pumpfactor,self.max_pump)
            if (pump_amount > np.abs(self.current_volume - tank.current_volume)):
               # #Handle case where amount to pump is minimal (less than difference in tanks)
               midpoint = np.average([self.current_volume, tank.current_volume])
               pump_amount = (midpoint - tank.current_volume)/2
            #   # self.virtual_volume -= (self.current_volume - midpoint)
            #   # tank.virtual_volume += (self.current_volume - midpoint)
            #   pass
            # else:
            #   #Actually do the pumping
            self.virtual_volume -= pump_amount
            tank.virtual_volume += pump_amount
      else:
        #NoPump
        pass



    def GetPumpAmount(currentVolume,threshold,pumpfactor,max_pump):
      amount = (np.sqrt((currentVolume-threshold))/pumpfactor)*max_pump
      #print(amount)
      if (amount > max_pump):
        amount = max_pump
      elif (amount < 0.0):
        amount = 0.0
      return amount

    def add_connection(self, connection):
        # Add a tank object to connections if not already present
        if connection not in self.connections:
            self.connections.append(connection)

    def remove_connection(self, connection):
        if connection in self.connections:
            self.connections.remove(connection)

def GenerateStorageGrid(gridx_dim, gridy_dim,maxvolume,threshold,maxpump,inletIds,outletIds):
    tankList = []
    # Create a 2D grid to store tank objects for easy access by coordinates
    tank_grid_2d = [[None for _ in range(gridy_dim)] for _ in range(gridx_dim)]

    # Step 1: Create all tanks and populate the 2D grid and flat list
    tank_id_counter = 0
    for x in range(gridx_dim):
        for y in range(gridy_dim):
            tank = StorageTank(tank_id_counter, maxvolume,threshold)
            tank_grid_2d[x][y] = tank
            tankList.append(tank)
            if (tank_id_counter in inletIds):
              tank.isInlet = True
            if (tank_id_counter in outletIds):
              tank.isOutlet = True
            tank_id_counter += 1

    # Step 2: Establish connections between tanks
    for x in range(gridx_dim):
        for y in range(gridy_dim):
            current_tank = tank_grid_2d[x][y]

            # Check all 8 possible neighbors (including diagonals)
            for dx in [-1, 0, 1]:
                for dy in [-1, 0, 1]:
                    if dx == 0 and dy == 0:  # Skip the current tank itself
                        continue

                    neighbor_x, neighbor_y = x + dx, y + dy

                    # Check if neighbor coordinates are within grid bounds
                    if 0 <= neighbor_x < gridx_dim and 0 <= neighbor_y < gridy_dim:
                        neighbor_tank = tank_grid_2d[neighbor_x][neighbor_y]
                        # Add neighbor tank object to current tank's connections
                        current_tank.add_connection(neighbor_tank)




    return tankList
def getDisplayGrid(gridx,gridy):
  x = np.linspace(0, gridx, gridx)
  y = np.linspace(0, gridy, gridy)
  xx,yy = np.meshgrid(x,y)
  return (xx,yy)

def RunSimulation(tankList,displaygrid,gridx, gridy,steps=1000):
    output_video_filename = 'tank_simulation.mp4'
    fourcc = cv2.VideoWriter_fourcc(*'mp4v') # Codec for MP4
    fps = 10 # Frames per second

    # Define a scaling factor for better visualization of the grid in the video
    scale_factor = 5
    display_width = gridx * scale_factor
    display_height = gridy * scale_factor

    video_writer = cv2.VideoWriter(output_video_filename, fourcc, fps, (display_width, display_height))

    for step in range(steps):
      print("Step #:" + str(step))

      #Reset Storage Conditions
      for tank in tankList:
          tank.virtual_volume = 0

      #Check Pumping
      for tank in tankList:
          for connection in tank.connections:
              connection.checkpump(tank)

      #Update Results
      for tank in tankList:
        if (tank.isInlet == True):
          tank.current_volume = tank.max_volume
        elif (tank.isOutlet == True):
          tank.current_volume = 0.0
        else:
          tank.current_volume += tank.virtual_volume
          if (tank.current_volume > tank.max_volume):
            tank.current_volume = tank.max_volume
        tank.virtual_volume = 0.0

      # Direct OpenCV rendering
      # Create a 2D array for current volumes
      ZZ = np.zeros((gridy, gridx), dtype=np.float32)
      for tank in tankList:
        col_idx = tank.id // gridy
        row_idx = tank.id % gridy
        ZZ[row_idx, col_idx] = tank.current_volume

      # Normalize ZZ values to 0-255 and apply colormap
      ZZ_normalized = (ZZ / 100.0 * 255).astype(np.uint8) # Assuming max_volume is 100
      img_colored = cv2.applyColorMap(ZZ_normalized, cv2.COLORMAP_JET)

      # Resize the image for better visualization
      img_resized = cv2.resize(img_colored, (display_width, display_height), interpolation=cv2.INTER_NEAREST)

      # Add step number as text
      cv2.putText(img_resized, f"Step: {step}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

      video_writer.write(img_resized)

    video_writer.release()
    print(f"Simulation video saved as {output_video_filename}")

tankList = list()

gridx = 80
gridy = 50

displaygrid = getDisplayGrid(gridx,gridy)

steps = 2000
threshold = 45.0
maxvolume = 100.0
maxpump = 5.0

inletIds = np.arange(gridy)
outletIds = np.arange(gridx*gridy-gridy,gridx*gridy)

inletIds = np.array([703,705,706,707])

tankList = GenerateStorageGrid(gridx, gridy,maxvolume,threshold,maxpump,inletIds,outletIds)

for tank in tankList[1].connections:
    print(f"Tank ID: {tank.id}, Current Volume: {tank.current_volume},Max Volume: {tank.max_volume}")

RunSimulation(tankList,displaygrid, gridx, gridy, steps=steps)

import matplotlib.pyplot as plt
import numpy as np

# 1. Create vectors
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)

# 2. Generate meshgrid
XX, YY = np.meshgrid(x, y)

# 3. Calculate Z (a 2D array)
ZZ = np.sin(np.sqrt(XX**2 + YY**2))

# 4. Plot with colormap
plt.pcolormesh(XX, YY, ZZ, cmap='viridis', shading='auto')
plt.colorbar(label='Z Value') # Add scale
plt.show()

z = np.arange(10)


test = 5

if (test in z):
  print("true")

